/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.avro.basics;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Account extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Account\",\"namespace\":\"com.avro.basics\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"category\",\"type\":\"string\"},{\"name\":\"accountTitle\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.CharSequence category;
  @Deprecated public java.lang.CharSequence accountTitle;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Account() {}

  /**
   * All-args constructor.
   */
  public Account(java.lang.CharSequence name, java.lang.CharSequence category, java.lang.CharSequence accountTitle) {
    this.name = name;
    this.category = category;
    this.accountTitle = accountTitle;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return category;
    case 2: return accountTitle;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: category = (java.lang.CharSequence)value$; break;
    case 2: accountTitle = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'category' field.
   */
  public java.lang.CharSequence getCategory() {
    return category;
  }

  /**
   * Sets the value of the 'category' field.
   * @param value the value to set.
   */
  public void setCategory(java.lang.CharSequence value) {
    this.category = value;
  }

  /**
   * Gets the value of the 'accountTitle' field.
   */
  public java.lang.CharSequence getAccountTitle() {
    return accountTitle;
  }

  /**
   * Sets the value of the 'accountTitle' field.
   * @param value the value to set.
   */
  public void setAccountTitle(java.lang.CharSequence value) {
    this.accountTitle = value;
  }

  /** Creates a new Account RecordBuilder */
  public static com.avro.basics.Account.Builder newBuilder() {
    return new com.avro.basics.Account.Builder();
  }
  
  /** Creates a new Account RecordBuilder by copying an existing Builder */
  public static com.avro.basics.Account.Builder newBuilder(com.avro.basics.Account.Builder other) {
    return new com.avro.basics.Account.Builder(other);
  }
  
  /** Creates a new Account RecordBuilder by copying an existing Account instance */
  public static com.avro.basics.Account.Builder newBuilder(com.avro.basics.Account other) {
    return new com.avro.basics.Account.Builder(other);
  }
  
  /**
   * RecordBuilder for Account instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Account>
    implements org.apache.avro.data.RecordBuilder<Account> {

    private java.lang.CharSequence name;
    private java.lang.CharSequence category;
    private java.lang.CharSequence accountTitle;

    /** Creates a new Builder */
    private Builder() {
      super(com.avro.basics.Account.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.avro.basics.Account.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.category)) {
        this.category = data().deepCopy(fields()[1].schema(), other.category);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.accountTitle)) {
        this.accountTitle = data().deepCopy(fields()[2].schema(), other.accountTitle);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Account instance */
    private Builder(com.avro.basics.Account other) {
            super(com.avro.basics.Account.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.category)) {
        this.category = data().deepCopy(fields()[1].schema(), other.category);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.accountTitle)) {
        this.accountTitle = data().deepCopy(fields()[2].schema(), other.accountTitle);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public com.avro.basics.Account.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'name' field */
    public com.avro.basics.Account.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'category' field */
    public java.lang.CharSequence getCategory() {
      return category;
    }
    
    /** Sets the value of the 'category' field */
    public com.avro.basics.Account.Builder setCategory(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.category = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'category' field has been set */
    public boolean hasCategory() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'category' field */
    public com.avro.basics.Account.Builder clearCategory() {
      category = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'accountTitle' field */
    public java.lang.CharSequence getAccountTitle() {
      return accountTitle;
    }
    
    /** Sets the value of the 'accountTitle' field */
    public com.avro.basics.Account.Builder setAccountTitle(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.accountTitle = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'accountTitle' field has been set */
    public boolean hasAccountTitle() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'accountTitle' field */
    public com.avro.basics.Account.Builder clearAccountTitle() {
      accountTitle = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    public Account build() {
      try {
        Account record = new Account();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.category = fieldSetFlags()[1] ? this.category : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.accountTitle = fieldSetFlags()[2] ? this.accountTitle : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
